### ISSUE TITLE
SDK VERSION

### ISSUE THREAD

**Issue by ishant7007** [tripathis617/ASP_.Net_Framework_MVC_Book_Reading_Event_Management#1]
hey ,i'm using visual studios 2017 and sdk 3.1 is not supported can you suggest an alternative to run your project? (without me forced to install vs 2019).......or how to change the targeted sdk version. Thanks

**Comment by tripathis617** [comment]
[BookReadingEvents.zip](https://github.com/tripathis617/ASP_.Net_Framework_MVC_Book_Reading_Event_Management/files/6035456/BookReadingEvents.zip)
This file is in version 2.1 .net core which is supported in vs 2017

**Comment by tripathis617** [comment]
if you want to learn .net, I can provide some links
https://www.youtube.com/watch?v=fN0PZMI5VhU&list=PLaFzfwmPR7_JuVN71I9pEpN8JadDTh0rg
